---
- name: Ansible lab
  hosts: local
  gather_facts: true

  tasks:
    - name: Install some basic packages defined in variable "packages"
      become: true
      apt:
        update_cache: yes
        cache_valid_time: "{{ aptcachetime }}"
        pkg: "{{ packages }}"

    - name: Enable Nginx service, ensure it is not masked and start it
      become: true
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        masked: no
        state: started

    - name: Create {{ app_dir }} directory if it does not exist
      become: true
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: "755"

    - name: Download Java app to {{ app_dir }}/{{ app_file }}
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/devops-practice-files/systemd/ServicesLab-0.0.1.jar
        dest: "{{ app_dir }}/{{ app_file }}"
        owner: "{{ ansible_user_id }}"
        mode: "644"

    - name: Create app user
      become: true
      ansible.builtin.user:
        name: "{{ app_user }}"
        comment: "Java app user"
        state: present

    - name: Create a Java App Unit
      become: true
      notify:
      - Reload Systemd
      ansible.builtin.template:
        dest: /etc/systemd/system/sample.service
        src: ./templates/app.service.j2
        mode: "644"
        owner: root
        group: root

    - name: Enable sample.service, ensure it is not masked and start it
      become: true
      ansible.builtin.systemd:
        name: sample
        enabled: yes
        masked: no
        state: started

    - name: Create a Nginx config
      become: true
      ansible.builtin.template:
        dest: /etc/nginx/nginx.conf
        src: ./templates/nginx.conf.j2
        mode: "644"
        owner: root
        group: root

    - name: Restart Nginx
      become: true
      ansible.builtin.systemd:
        name: nginx
        daemon_reload: yes
        state: restarted
  
  handlers:
    - name: Reload Systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: yes   
